language: node_js

node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

env: CXX="g++-4.8" CC="gcc-4.8"
