version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10
  steps:
    - checkout
    - run: npm install --no-optional
    - run: npm test

jobs:
  test-node6:
    docker:
      - image: circleci/node:6
    <<: *defaults

  test-node8:
    docker:
      - image: circleci/node:8
    <<: *defaults

  test-node10:
    <<: *defaults

  release:
    <<: *defaults
    steps:
      - checkout
      - run: npm install
      - run: npm run semantic-release || true

workflows:
  version: 2

  test_and_release:
    jobs:
      - test-node6
      - test-node8
      - test-node10
      - release:
          requires:
            - test-node6
            - test-node8
            - test-node10
          filters:
            branches:
              only: master
